version: '3'

services:
  asynctmdb:
    build: .
    image: lycantropos/asynctmdb:latest
    volumes:
      - .:/asynctmdb/
    environment:
      - TMDB_API_KEY=$TMDB_API_KEY
      - TMDB_USER_NAME=$TMDB_USER_NAME
      - TMDB_USER_PASSWORD=$TMDB_USER_PASSWORD
    entrypoint: python3
    command: setup.py test
    extra_hosts:
      - "dockerhost:$DOCKERHOST"  # for debugging
